// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using powerkit3000.data;

#nullable disable

namespace powerkit3000.data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250923075359_AddChineseFieldsToKickstarterProject")]
    partial class AddChineseFieldsToKickstarterProject
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("powerkit3000.data.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("ParentName")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("powerkit3000.data.Models.Creator", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Creators");
                });

            modelBuilder.Entity("powerkit3000.data.Models.KickstarterProject", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("BackersCount")
                        .HasColumnType("integer");

                    b.Property<string>("Blurb")
                        .HasColumnType("text");

                    b.Property<string>("BlurbCn")
                        .HasColumnType("text");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("ConvertedPledgedAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("CountryDisplayableName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("CurrencySymbol")
                        .HasColumnType("text");

                    b.Property<bool?>("CurrencyTrailingCode")
                        .HasColumnType("boolean");

                    b.Property<string>("CurrentCurrency")
                        .HasColumnType("text");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("DisableCommunication")
                        .HasColumnType("boolean");

                    b.Property<decimal>("FxRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Goal")
                        .HasColumnType("numeric");

                    b.Property<bool?>("IsDisliked")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsInPostCampaignPledgingPhase")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsLaunched")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsLiked")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsStarrable")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LaunchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NameCn")
                        .HasColumnType("text");

                    b.Property<decimal>("PercentFunded")
                        .HasColumnType("numeric");

                    b.Property<string>("Photo")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("Pledged")
                        .HasColumnType("numeric");

                    b.Property<bool?>("PrelaunchActivated")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("Spotlight")
                        .HasColumnType("boolean");

                    b.Property<bool?>("StaffPick")
                        .HasColumnType("boolean");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("StateChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("StaticUsdRate")
                        .HasColumnType("numeric");

                    b.Property<string>("Urls")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("UsdExchangeRate")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UsdPledged")
                        .HasColumnType("numeric");

                    b.Property<string>("UsdType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("LocationId");

                    b.ToTable("KickstarterProjects");
                });

            modelBuilder.Entity("powerkit3000.data.Models.Location", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("DisplayableName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("powerkit3000.data.Models.KickstarterProject", b =>
                {
                    b.HasOne("powerkit3000.data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("powerkit3000.data.Models.Creator", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("powerkit3000.data.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Category");

                    b.Navigation("Creator");

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
